# Generated by Django 4.1.7 on 2023-07-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can', '0004_post_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('name', models.CharField(max_length=300, null=True)),
                ('adres', models.CharField(max_length=300, null=True)),
                ('publishing_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yayınlanma Tarihi')),
                ('date', models.CharField(max_length=300, null=True)),
                ('category', models.CharField(default='website', max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
