# Generated by Django 4.1.7 on 2023-07-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('can', '0005_experience_alter_post_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
