# Generated by Django 4.2.5 on 2023-09-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can', '0005_alter_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary_tr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
