# Generated by Django 4.2.5 on 2023-09-18 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('can', '0006_post_summary_en_post_summary_tr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='summary_tr',
        ),
    ]
