# Generated by Django 4.1.7 on 2023-07-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can', '0006_delete_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='adres',
            new_name='firm',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='category',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='content',
            field=models.TextField(max_length=500, null=True, verbose_name='explanation'),
        ),
    ]
