# Generated by Django 4.1.7 on 2023-07-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can', '0007_rename_adres_portfolio_firm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='content',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='explanation'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
