# Generated by Django 4.2.4 on 2023-08-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can', '0008_alter_portfolio_content_alter_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary_tr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
