# Generated by Django 4.2.5 on 2023-09-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can', '0008_post_summary_en_post_summary_tr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='can.category'),
        ),
    ]
