# Generated by Django 4.2.7 on 2024-01-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can', '0010_remove_post_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary_en',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary_tr',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
