# Generated by Django 4.2.4 on 2023-08-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can', '0010_post_read_en_post_read_tr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='read_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='read_tr',
        ),
        migrations.AddField(
            model_name='post',
            name='read_time_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='read_time_tr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
