# Generated by Django 4.2.4 on 2023-08-05 08:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('can', '0011_remove_post_read_en_remove_post_read_tr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='interest',
            field=ckeditor.fields.RichTextField(default='', null=True),
        ),
    ]
