# Generated by Django 4.2.7 on 2024-01-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can', '0011_alter_post_summary_alter_post_summary_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary_tr',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
