# Generated by Django 4.2.4 on 2023-08-05 08:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('can', '0012_resume_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='interest_en',
            field=ckeditor.fields.RichTextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='interest_tr',
            field=ckeditor.fields.RichTextField(default='', null=True),
        ),
    ]
