# Generated by Django 4.2.9 on 2024-01-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can', '0013_alter_post_summary_alter_post_summary_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='other_categories',
            field=models.ManyToManyField(related_name='Other_categories', to='can.category'),
        ),
    ]
